name: release-npm

on:
  workflow_run:
    workflows: ["build-matrix"]
    types: [completed]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: false

jobs:

  publish-npm:
    name: Publish npm
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd unzip gh

      - name: Pack and publish
        shell: bash
        run: |
          set -euo pipefail
          tag="${{ github.event.workflow_run.head_branch }}"
          ./npm/mcp-getweb/pack_npm.sh --repo "${{ github.repository }}" "$tag" --dir ../../dist
